### ISSUE TITLE
hey is this a request faild error?

### ISSUE THREAD

**Issue by Kalmaegi** [kyler-harrison/bookbot-scrape#1]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.goodreads.com', port=443): Max retries exceeded with url: /review/list/99552017?shelf=currently-reading (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BCBB69F340>: Failed to establish a new connection: [WinError 10060]

**Comment by kyler-harrison** [comment]
Looks like it. Goodreads seems to block your ip address for a little while if you request too many pages in a short amount of time. I had more success scraping when I used the my_fake_useragent library (see gen_agent_headers() in ./utils.py) when I called requests.get() and did a short time-out between requests.

**Comment by Kalmaegi** [comment]
> 看起来像。如果您在短时间内请求太多页面，Goodreads 似乎会暂时阻止您的 IP 地址。当我使用 my_fake_useragent 库（请参阅 ./utils.py 中的 gen_agent_headers()）时，我获得了更多的成功，当我调用 requests.get() 并在请求之间进行了短暂的超时。

thanks!
